universe = docker
docker_image = pytorch/pytorch:2.3.1-cuda12.1-cudnn8-devel
executable = /opt/conda/bin/python
arguments = /home/atml_team034/tml26_task1/train_shadow.py
output = runlogs/mia.$(ClusterId).$(ProcId).out
error = runlogs/mia.$(ClusterId).$(ProcId).err
log = runlogs/mia.$(ClusterId).log
should_transfer_files = YES
request_GPUs = 1
request_CPUs = 1
request_memory = 4G
requirements = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted = true
queue 1